### ISSUE TITLE
Downloaded DePoolHelper.abi.json in wrong branch

### ISSUE THREAD

**Issue by yoztheripper** [INTONNATION/FreeTON-Rust-Node#30]
When installing the validator, the abi are downloaded from master branch but not in RUSTCUP_DEPOOL_--_DO_NOT_DEPLOY_ON_MAINNET

**Comment by azavodovsky** [comment]
Hey Yoztheripper!
Thanks for this mention, the fix has already been added to main branch. Let us know in case you find any additional struggles.
